### ISSUE TITLE
"Be specific" ending still gets question mark added

### ISSUE THREAD

**Issue by ProfessorO** [Deadpikle/pathfinder-bible-experience-prep-quiz-master#32]
See, for example, https://pbeprep.com/questions/7101/edit

The automatic addition of the question mark is very useful. However, the "be specific" specifier at the end might need to either be detected in a special way, or perhaps turned into a flag that adds a language-specific ending.

**Comment by Deadpikle** [comment]
This doesn't have a very thorough check or non-English check, you are correct. This would be a good opportunity to enhance the system with a more clever check.

The question you linked should be covered, though. See the below checks that are currently in the system.

https://github.com/Deadpikle/pathfinder-bible-experience-prep-quiz-master/blob/208d87c6f4413a39ef6516bbe0901c3fd6cccc67/views/user/quiz/take-quiz.twig#L453-L456

https://github.com/Deadpikle/pathfinder-bible-experience-prep-quiz-master/blob/master/app/Services/PDFGenerator.php#L18-L21

**Comment by Deadpikle** [comment]
Oh..there is a separate check before it messing with the logic, here. 🤦🏻 

https://github.com/Deadpikle/pathfinder-bible-experience-prep-quiz-master/blob/208d87c6f4413a39ef6516bbe0901c3fd6cccc67/views/user/quiz/take-quiz.twig#L450-L457

**Comment by Deadpikle** [comment]
Fixed, and bonus: finally got PHPUnit in the project for some better testing!

Thank you for the report.
