### ISSUE TITLE
Add optional countdown timer to quizzing

### ISSUE THREAD

**Issue by Deadpikle** [Deadpikle/pathfinder-bible-experience-prep-quiz-master#40]
"A countdown timer starts after the question has been read in English and Spanish. I believe the time is 30 seconds for 1-point questions, plus 15 extra seconds per point beyond that."

Should add this as an optional (opt-out) checkbox on the quiz setup screen, then feed through to the actual quiz page via POST.

**Comment by Deadpikle** [comment]
https://albert-gonzalez.github.io/easytimer.js/ looks like a nice library for a countdown timer.

**Comment by ProfessorO** [comment]
Details about timing are given at https://nadpbe.org/wp-content/uploads/2021/08/HowtoBibleExperience.pdf#page=15

**Comment by Deadpikle** [comment]
Here's the applicable snippet for historical purposes:
<img width="315" alt="Screen Shot 2022-01-29 at 5 28 57 PM" src="https://user-images.githubusercontent.com/5092399/161453843-a948fe4b-7502-45b0-99de-74c6ac89a513.png">
